syntax = "proto3";

package product;

service ProductService {
  rpc CreateProduct (CreateProductRequest) returns (ProductResponse);
  rpc ListProducts (ListProductsRequest) returns (ProductListResponse);
  rpc UpdateProduct (UpdateProductRequest) returns (ProductResponse);
  rpc DeleteProduct (DeleteProductRequest) returns (Empty);
}

message Product {
  int32 id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
}

message CreateProductRequest {
  string name = 1;
  string description = 2;
  double price = 3;
}

message UpdateProductRequest {
  int32 id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
}

message ListProductsRequest {
  int32 limit = 1;
  int32 offset = 2;
}

message ProductResponse {
  Product product = 1;
}

message ProductListResponse {
  repeated Product data = 1;
  int32 total = 2;
}

message DeleteProductRequest {
  int32 id = 1;
}

message Empty {}
